import { useState } from "react";
import { Award, Download, Loader2, Search } from "lucide-react";
import { usePageMeta } from "../../hooks/usePageMeta";
import { lookupCertificate, type CertificateResult } from "../../lib/supabase/certificates";
import { usePortal } from "../../providers/PortalProvider";
import { tx } from "../../utils/i18n";

export function CertificateLookupPage(){
  const {t,isRtl}=usePortal(); const [identifier,setIdentifier]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<CertificateResult|null>(null); const [celebrate,setCelebrate]=useState(false);
  usePageMeta(tx("شهادات حضور المحاضرات | مستشفى الحديثة العام","Lecture certificates | Hadetha General Hospital"),tx("استخرج شهادة حضورك برقم الهوية أو الرقم الوظيفي.","Retrieve your attendance certificate using your ID or employee number."));
  const submit=async(e:React.FormEvent)=>{e.preventDefault(); if(!identifier.trim())return; setBusy(true);setError(""); const r=await lookupCertificate(identifier);setBusy(false); if(!r.data){setError(r.error==="not_found"?t(tx("لم نجد شهادة مرتبطة بهذا الرقم. تأكد من الرقم وحاول مجددًا.","No certificate was found for this number. Check it and try again.")):t(tx("تعذر الاتصال بالخدمة. حاول لاحقًا.","The service is unavailable. Try again later.")));return;} setCelebrate(true); window.setTimeout(()=>{setResult(r.data);setCelebrate(false)},1800);};
  return <div className="certificate-lookup-page" dir={isRtl?"rtl":"ltr"}>
    {celebrate?<div className="certificate-thanks" role="status"><span><Award size={58}/></span><h1>{t(tx("شكرًا لحضورك!","Thank you for attending!"))}</h1><p>{t(tx("نسعد بمشاركتك ونتمنى لك دوام التوفيق","We appreciate your participation and wish you continued success."))}</p></div>:null}
    <header className="certificate-mobile-header"><img src="/assets/brand/hospital-logo-white.webp" alt={t(tx("مستشفى الحديثة العام","Hadetha General Hospital"))}/><p>{t(tx("إدارة الشؤون الأكاديمية والتدريب","Academic Affairs & Training"))}</p></header>
    <main className="certificate-lookup-main">
      {!result?<section className="certificate-search-card"><span className="certificate-search-icon"><Award size={32}/></span><h1>{t(tx("استخرج شهادة حضورك","Get your attendance certificate"))}</h1><p>{t(tx("أدخل رقم الهوية أو الرقم الوظيفي المسجل لدى إدارة التدريب.","Enter the national ID or employee number registered with Training."))}</p><form onSubmit={submit}><label htmlFor="certificate-id">{t(tx("رقم الهوية أو الرقم الوظيفي","National ID or employee number"))}</label><input id="certificate-id" value={identifier} onChange={e=>setIdentifier(e.target.value.replace(/\D/g,""))} inputMode="numeric" autoComplete="off" placeholder={t(tx("اكتب الرقم هنا","Enter the number"))}/>{error?<p className="attend-error" role="alert">{error}</p>:null}<button className="btn btn-primary" disabled={busy||!identifier}>{busy?<Loader2 className="spin" size={18}/>:<Search size={18}/>} {t(tx("عرض الشهادة","View certificate"))}</button></form></section>:
      <section className="certificate-result"><div className="lookup-cert-sheet">{result.template_url?<img src={result.template_url} alt=""/>:<div className="lookup-cert-decoration"/>}<div className="lookup-cert-brand"><img src="/assets/brand/hospital-logo.webp" alt=""/><strong>{t(tx("شهادة حضور","Certificate of Attendance"))}</strong></div><p>{t(tx("تشهد إدارة الشؤون الأكاديمية والتدريب بمستشفى الحديثة العام بأن","Academic Affairs & Training at Hadetha General Hospital certifies that"))}</p><h2>{result.full_name}</h2><p>{t(tx("قد حضر/ت محاضرة بعنوان","attended the lecture entitled"))}</p><h3>{t(tx(result.title_ar,result.title_en||result.title_ar))}</h3><time>{new Intl.DateTimeFormat(isRtl?"ar-SA":"en-GB",{dateStyle:"long"}).format(new Date(result.lecture_date))}</time></div><div className="certificate-result-actions"><button className="btn btn-primary" onClick={()=>window.print()}><Download size={18}/>{t(tx("حفظ / طباعة الشهادة","Save / print certificate"))}</button><button className="btn btn-ghost" onClick={()=>{setResult(null);setIdentifier("")}}>{t(tx("البحث عن شهادة أخرى","Find another certificate"))}</button></div></section>}
    </main><footer>{t(tx("مستشفى الحديثة العام — تجمع الجوف الصحي","Hadetha General Hospital — Al-Jouf Health Cluster"))}</footer>
  </div>;
}
