import { useEffect,useState } from "react";
import { Plus,Save,Trash2 } from "lucide-react";
import { usePortal } from "../../providers/PortalProvider";
import { tx } from "../../utils/i18n";
import { deleteCertificateRecipient,fetchCertificateEvents,fetchCertificateRecipients,saveCertificateEvent,saveCertificateRecipient,type CertificateEvent,type CertificateRecipient } from "../../lib/supabase/certificates";
type Notify=(m:string,tone?:"success"|"error"|"info")=>void;
const blankRecipient=(event_id:string):Partial<CertificateRecipient>=>({event_id,full_name:"",national_id:"",employee_number:""});
export function AdminCertificates({notify}:{notify:Notify}){const {t}=usePortal();const [events,setEvents]=useState<CertificateEvent[]>([]);const [eventId,setEventId]=useState("");const [rows,setRows]=useState<CertificateRecipient[]>([]);const [draft,setDraft]=useState<Partial<CertificateRecipient>>(blankRecipient(""));const current=events.find(e=>e.id===eventId);
 const loadEvents=()=>fetchCertificateEvents().then(es=>{setEvents(es);setEventId(v=>v||es[0]?.id||"")}); useEffect(()=>{void loadEvents()},[]);useEffect(()=>{if(eventId){fetchCertificateRecipients(eventId).then(setRows);setDraft(blankRecipient(eventId))}},[eventId]);
 const saveEvent=async(p:Partial<CertificateEvent>)=>{if(!current)return;const r=await saveCertificateEvent({...current,...p});if(r.error)notify(r.error,"error");else{notify(t(tx("تم حفظ بيانات الشهادة.","Certificate details saved.")),"success");loadEvents()}};
 const savePerson=async(r:Partial<CertificateRecipient>)=>{const out=await saveCertificateRecipient(r);if(out.error)notify(out.error,"error");else{notify(t(tx("تم حفظ الموظف.","Employee saved.")),"success");fetchCertificateRecipients(eventId).then(setRows);setDraft(blankRecipient(eventId))}};
 return <div><div className="admin-page-heading"><div><h1>{t(tx("شهادات المحاضرات","Lecture certificates"))}</h1><p>{t(tx("إدارة أسماء المستحقين وبيانات الشهادة والقالب.","Manage eligible employees, certificate details, and template."))}</p></div><a className="btn btn-secondary" href="/certificates" target="_blank">{t(tx("فتح صفحة الشهادات","Open certificate page"))}</a></div>
 <div className="admin-panel admin-form"><button className="btn btn-secondary field-wide" onClick={async()=>{const r=await saveCertificateEvent({title_ar:"شهادة جديدة",title_en:"New certificate",lecture_date:new Date().toISOString().slice(0,10),template_url:null,is_active:true});if(r.error)notify(r.error,"error");else loadEvents()}}><Plus size={16}/>{t(tx("إضافة شهادة جديدة","Add new certificate"))}</button><label className="field-wide">{t(tx("المحاضرة","Lecture"))}<select value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.title_ar}</option>)}</select></label>{current?<><label>{t(tx("اسم الشهادة / المحاضرة","Certificate / lecture name"))}<input value={current.title_ar} onChange={e=>setEvents(es=>es.map(x=>x.id===current.id?{...x,title_ar:e.target.value}:x))}/></label><label>{t(tx("الاسم بالإنجليزية","English name"))}<input value={current.title_en} onChange={e=>setEvents(es=>es.map(x=>x.id===current.id?{...x,title_en:e.target.value}:x))}/></label><label>{t(tx("التاريخ","Date"))}<input type="date" value={current.lecture_date} onChange={e=>setEvents(es=>es.map(x=>x.id===current.id?{...x,lecture_date:e.target.value}:x))}/></label><label>{t(tx("رابط صورة القالب","Template image URL"))}<input value={current.template_url??""} onChange={e=>setEvents(es=>es.map(x=>x.id===current.id?{...x,template_url:e.target.value}:x))}/></label><button className="btn btn-primary field-wide" onClick={()=>saveEvent({})}><Save size={16}/>{t(tx("حفظ الشهادة","Save certificate"))}</button></>:null}</div>
 <div className="admin-panel"><h2>{t(tx("إضافة موظف","Add employee"))}</h2><div className="certificate-recipient-grid"><input placeholder={t(tx("الاسم الكامل","Full name"))} value={draft.full_name??""} onChange={e=>setDraft({...draft,full_name:e.target.value})}/><input placeholder={t(tx("رقم الهوية","National ID"))} value={draft.national_id??""} onChange={e=>setDraft({...draft,national_id:e.target.value})}/><input placeholder={t(tx("الرقم الوظيفي","Employee number"))} value={draft.employee_number??""} onChange={e=>setDraft({...draft,employee_number:e.target.value})}/><button className="btn btn-primary" onClick={()=>savePerson(draft)}><Plus size={16}/>{t(tx("إضافة","Add"))}</button></div></div>
 <div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>{t(tx("الاسم","Name"))}</th><th>{t(tx("الهوية","National ID"))}</th><th>{t(tx("الرقم الوظيفي","Employee no."))}</th><th>{t(tx("إجراءات","Actions"))}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><input value={r.full_name} onChange={e=>setRows(xs=>xs.map(x=>x.id===r.id?{...x,full_name:e.target.value}:x))}/></td><td><input value={r.national_id??""} onChange={e=>setRows(xs=>xs.map(x=>x.id===r.id?{...x,national_id:e.target.value}:x))}/></td><td><input value={r.employee_number??""} onChange={e=>setRows(xs=>xs.map(x=>x.id===r.id?{...x,employee_number:e.target.value}:x))}/></td><td><button className="btn btn-ghost" onClick={()=>savePerson(r)}><Save size={15}/></button><button className="btn btn-ghost" onClick={async()=>{await deleteCertificateRecipient(r.id);setRows(xs=>xs.filter(x=>x.id!==r.id))}}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div>}
